use strum_macros::EnumString;
use std::convert::AsRef;
use serde::{Serialize, Deserialize};

// Define the layout action types
#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumString, strum_macros::AsRefStr, strum_macros::VariantNames, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
#[strum(serialize_all = "kebab-case")]
pub enum LayoutAction {
    LeftHalf,
    RightHalf,
    CenterHalf,
    TopHalf,
    BottomHalf,
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
    FirstThird,
    CenterThird,
    LastThird,
    FirstTwoThirds,
    LastTwoThirds,
    Maximize,
    AlmostMaximize,
    MaximizeHeight,
    Smaller,
    Larger,
    Center,
    CenterProminently,
    Restore,
    NextDisplay,
    PreviousDisplay,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    FirstFourth,
    SecondFourth,
    ThirdFourth,
    LastFourth,
    FirstThreeFourths,
    LastThreeFourths,
    TopLeftSixth,
    TopCenterSixth,
    TopRightSixth,
    BottomLeftSixth,
    BottomCenterSixth,
    BottomRightSixth,
    Specified,
    ReverseAll,
    TopLeftThird,
    TopRightThird,
    BottomLeftThird,
    BottomRightThird,
    TileAll,
    CascadeAll,
    CascadeActiveApp,
}