use serde::{Deserialize, Serialize};

// Define the layout action types
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum LayoutAction {
    LeftHalf,
    RightHalf,
    CenterHalf,
    TopHalf,
    BottomHalf,
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
    FirstThird,
    CenterThird,
    LastThird,
    FirstTwoThirds,
    LastTwoThirds,
    Maximize,
    AlmostMaximize,
    MaximizeHeight,
    Smaller,
    Larger,
    Center,
    CenterProminently,
    Restore,
    NextDisplay,
    PreviousDisplay,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    FirstFourth,
    SecondFourth,
    ThirdFourth,
    LastFourth,
    FirstThreeFourths,
    LastThreeFourths,
    TopLeftSixth,
    TopCenterSixth,
    TopRightSixth,
    BottomLeftSixth,
    BottomCenterSixth,
    BottomRightSixth,
    TopLeftThird,
    TopRightThird,
    BottomLeftThird,
    BottomRightThird,
    ApplyZone(u32),
    ActivateLayout(String),
}
