// TODO: Get this from rust generated somehow?

export enum LayoutAction {
  LeftHalf = 'left-half',
  RightHalf = 'right-half',
  CenterHalf = 'center-half',
  TopHalf = 'top-half',
  BottomHalf = 'bottom-half',
  TopLeft = 'top-left',
  TopRight = 'top-right',
  BottomLeft = 'bottom-left',
  BottomRight = 'bottom-right',
  FirstThird = 'first-third',
  CenterThird = 'center-third',
  LastThird = 'last-third',
  FirstTwoThirds = 'first-two-thirds',
  LastTwoThirds = 'last-two-thirds',
  Maximize = 'maximize',
  AlmostMaximize = 'almost-maximize',
  MaximizeHeight = 'maximize-height',
  Smaller = 'smaller',
  Larger = 'larger',
  Center = 'center',
  CenterProminently = 'center-prominently',
  Restore = 'restore',
  NextDisplay = 'next-display',
  PreviousDisplay = 'previous-display',
  MoveLeft = 'move-left',
  MoveRight = 'move-right',
  MoveUp = 'move-up',
  MoveDown = 'move-down',
  FirstFourth = 'first-fourth',
  SecondFourth = 'second-fourth',
  ThirdFourth = 'third-fourth',
  LastFourth = 'last-fourth',
  FirstThreeFourths = 'first-three-fourths',
  LastThreeFourths = 'last-three-fourths',
  TopLeftSixth = 'top-left-sixth',
  TopCenterSixth = 'top-center-sixth',
  TopRightSixth = 'top-right-sixth',
  BottomLeftSixth = 'bottom-left-sixth',
  BottomCenterSixth = 'bottom-center-sixth',
  BottomRightSixth = 'bottom-right-sixth',
  TopLeftThird = 'top-left-third',
  TopRightThird = 'top-right-third',
  BottomLeftThird = 'bottom-left-third',
  BottomRightThird = 'bottom-right-third',
} 