// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { auto_start: boolean, start_minimized: boolean, close_to_system_tray: boolean, show_layout_activation_notification: boolean, };
