// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { auto_start: boolean, start_minimized: boolean, close_to_system_tray: boolean, show_layout_activation_notification: boolean, zone_drag_modifier_key: string | null, 
/**
 * When true, show the zone overlay during drag-and-drop (when modifier is held). When false, zones still apply on drop but no visual indicator is shown.
 */
show_zone_drag_overlay: boolean, 
/**
 * Opacity of the zone overlay during drag (0.0–1.0). Default 0.25 when unset.
 */
zone_overlay_opacity: number, };
