// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Zone } from "./Zone";

export type ZoneLayout = { id: string, name: string, zones: Array<Zone>, screenWidth: number | null, screenHeight: number | null, };
